#!/usr/bin/env bash
#SBATCH --account=mbetegon
#SBATCH --job-name=job_name
#SBATCH --output=log.out
#SBATCH --ntasks-per-node=24
#SBATCH --mem=48GB
#SBATCH --time=24:00:00
#SBATCH --cluster=smp
#SBATCH --partition=smp
#SBATCH --nodes=1

[command to run here]
python symm_mpnn_relax.py --input_pdb ./mpnn_input/C5_3_9_dn12_trunc_AB_0001_renum.pdb --symmdef ./C5.symm --output_base C5_3_9_dn12_cycles_4 --job_name cycles_job --num_cycles 100
